### PR TITLE
Welcome users on talk page

### PR DESCRIPTION
**Pull request by apple502j**
If $wgAutoWelcomeNewUsers is true (default) it automatically creates talk page to welcome the user.

### CODE REVIEW

**Comment by Naleksuh** [comment]
I think this needs discussion-- I found it one of the most annoying features and there is a reason I did not add it

**Comment by Naleksuh** [comment]
The goal here should not be to make the new system exactly like the old one-- redesigning stuff like that is good and part of the reason this was made (not just for technical redesigns but the entirety). If the accepting admin wants to welcome the user, they can do so, but having having FORCED welcomes be a feature (and much less enabled by default) is not a good idea. So, I oppose this merge request. Please let me know if you do not agree

**Comment by apple502j** [comment]
Honestly I have never seen one who thinks welcoming is annoying. Even if it's optional, the admins will still enable that option.

**Comment by Naleksuh** [comment]
If an admin wants to welcome a user, they can simply add the welcome template (most admins actually already do this on English Scratch Wiki). What you are proposing is _forcing_ admins to welcome a user. While I am not an administrator on Scratch Wiki, if I was one I certainly would not want this welcome and I would author request delete any talk pages this extension created.

Regardless, I think I should put my personal beliefs aside here, and let's stick to the facts: any admin that wants to welcome a user can do so, but there is no sense in having it be done automatically and involuntarily. Yes, the previous extension did this, but this is not the previous extension.

**Review by jacob-g — APPROVED** [review]

**Pull request merged**
